apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: uaicontrole-ingress
    # nginx.ingress.kubernetes.io/configuration-snippet: |
    #   proxy_http_version 1.1;
    #   proxy_set_header Upgrade "websocket";
    #   proxy_set_header Connection "Upgrade";
spec:
  backend:
    serviceName: jenkins
    servicePort: 32256